// Generated by packages/opencode/script/build.ts from the root .env (BRAND_*).
// Do not edit by hand. Runtime process.env / .env values still take precedence
// over these baked defaults; they only matter in compiled binaries that ship
// without a .env file.
export const BRAND_VARS: Record<string, string> | null = {
  "BRAND_NAME": "Shark",
  "BRAND_SHORT": "SK",
  "BRAND_ORG": "SUJA Healthtech",
  "BRAND_ORG_WEBSITE": "https://sujahealthtech.com",
  "BRAND_ORG_ABOUT": "Founded in 1999 in Hyderabad, India, by CEO Surya Kuchimanchi, Suja HealthTech (formerly Suja Associates) is an AI-powered healthcare technology company specializing in hospital management systems, AI digital colposcopy solutions, and revenue cycle management.",
}
