// Brand identity for the product. All user-facing product naming funnels
// through this module so a rebrand is a change to `.env` (BRAND_*) plus a swap
// of the static SVG/i18n assets.
//
// The main entry is browser-safe: it reads `process.env` when present (Node /
// Bun / built server) and otherwise falls back to the defaults. Consumers that
// run under Node or Bun can import `@opencode-ai/brand/env` instead, which adds
// a magical `.env` lookup walking up from the working directory so a single
// root-level `.env` drives branding regardless of `--cwd`.
//
// Values baked into compiled binaries via `defaults.gen.ts` (regenerated by
// `packages/opencode/script/build.ts` from the root `.env`) sit between the
// hardcoded defaults and the runtime env: env > baked > hardcoded.

export type BrandVars = {
  name: string
  tagline: string
  title: string
  short: string
  org: string
  orgWebsite: string | undefined
  orgAbout: string | undefined
  split: number | undefined
}

import { BRAND_VARS as BAKED } from "./defaults.gen"

const DEFAULTS: BrandVars = {
  name: "Shark",
  tagline: "The open source AI coding agent.",
  title: "Shark",
  short: "SK",
  org: "Shark",
  orgWebsite: undefined,
  orgAbout: undefined,
  split: undefined,
}

const envOf = (key: string): string | undefined => {
  if (typeof process === "undefined") return undefined
  return process.env[key]
}

const str = (key: string, fallback: string) => envOf(key)?.trim() || fallback

const opt = (key: string): string | undefined => envOf(key)?.trim() || undefined

const num = (key: string): number | undefined => {
  const value = Number(envOf(key))
  return Number.isFinite(value) ? value : undefined
}

let vars: BrandVars = {
  name: str("BRAND_NAME", BAKED?.name ?? DEFAULTS.name),
  tagline: str("BRAND_TAGLINE", BAKED?.tagline ?? DEFAULTS.tagline),
  title: str("BRAND_TITLE", BAKED?.title ?? DEFAULTS.title),
  short: str("BRAND_SHORT", BAKED?.short ?? DEFAULTS.short),
  org: str("BRAND_ORG", BAKED?.org ?? DEFAULTS.name),
  orgWebsite: opt("BRAND_ORG_WEBSITE") ?? BAKED?.orgWebsite,
  orgAbout: opt("BRAND_ORG_ABOUT") ?? BAKED?.orgAbout,
  split: num("BRAND_SPLIT") ?? (BAKED?.split ? Number(BAKED.split) || undefined : undefined),
}

export function setBrandVars(partial: Partial<BrandVars>) {
  const next = Object.fromEntries(Object.entries(partial).filter(([, value]) => value !== undefined))
  vars = { ...vars, ...next }
}

export const Brand = {
  get name() {
    return vars.name
  },
  get command() {
    return vars.name.toLowerCase()
  },
  get tagline() {
    return vars.tagline
  },
  get title() {
    return vars.title
  },
  get short() {
    return vars.short
  },
  get org() {
    return vars.org
  },
  get orgWebsite() {
    return vars.orgWebsite
  },
  get orgAbout() {
    return vars.orgAbout
  },
}

// -- Block glyph font ----------------------------------------------------

// 3-row block letters in the style of the built-in terminal wordmark. Only
// "█" (full block), "▀" (top half), "▄" (bottom half) and spaces are used so
// the same grid can drive both ASCII art (TUI/CLI) and SVG rendering (web).
const GLYPHS: Record<string, readonly [string, string, string]> = {
  A: ["█  █", "█▀▀█", "▀  ▀ "],
  B: ["█▀▀▄", "█  █", "█▀▀▄"],
  C: ["█▀▀▀", "█   ", "▀▀▀▀"],
  D: ["█▀▀▄", "█  █", "█▀▀▀"],
  E: ["█▀▀█", "█▀▀▀", "█▀▀▀"],
  F: ["█▀▀█", "█▀▀▀", "█   "],
  G: ["█▀▀▀", "█  █", "▀▀▀▄"],
  H: ["█  █", "█▀▀█", "█  █"],
  I: ["▀▀▀▀", " ▀█ ", "▀▀▀▄"],
  J: ["▀▀▀▀", "  █ ", "█▀▀▀"],
  K: ["█  █", "█▀▀▄", "█  █"],
  L: ["█   ", "█   ", "█▀▀█"],
  M: ["█▀▀▄", "█  █", "█  █"],
  N: ["█▀▀▄", "█  █", "▀  ▀"],
  O: ["█▀▀█", "█  █", "▀▀▀▄"],
  P: ["█▀▀█", "█  █", "█▀▀▀"],
  Q: ["█▀▀█", "█  █", "█▀▀▄"],
  R: ["█▀▀▄", "█▀▀▄", "█  █ "],
  S: ["█▀▀▀", "█   █", "▀▀▀▄ "],
  T: ["█▀▀▀", " █  ", " █  "],
  U: ["█  █", "█  █", "▀▀▀▄"],
  V: ["█  █", "█  █", " ▀▀ "],
  W: ["█  █", "█  █", "█▀▀▄"],
  X: ["█  █", " ▀█ ", "█  █"],
  Y: ["█  █", " ▀█ ", " █  "],
  Z: ["█▀▀▄", " ▀█ ", "▄▀▀▀"],
}

const letter = (char: string): readonly string[] => {
  const upper = char.toUpperCase()
  if (upper in GLYPHS) return GLYPHS[upper] ?? []
  if (upper === " ") return ["", "", ""]
  return GLYPHS.O ?? []
}

// Split point for the two-tone colored wordmark ("open"|"code" becomes
// "SH"|"ARK" for "Shark"). Overridable via BRAND_SPLIT (character index).
const splitIndex = (name: string): number => {
  const fromSplit = vars.split
  if (fromSplit && fromSplit > 0 && fromSplit < name.length) return fromSplit
  return Math.round(name.length / 2)
}

const textRows = (text: string): string[] => {
  const rows = ["", "", ""]
  for (const char of text) {
    const glyph = letter(char)
    for (let row = 0; row < 3; row++) {
      rows[row] += (rows[row] ? " " : "") + (glyph[row] ?? "").trimEnd()
    }
  }
  return rows
}

// -- Renderers -----------------------------------------------------------

// Two-tone glyphs matching the legacy { left, right } logo shape used by the
// TUI renderer and CLI banner. Row 0 is the decorative mark row.
export function brandGlyphs(name = Brand.name): { left: string[]; right: string[] } {
  const upper = name.toUpperCase()
  const mid = splitIndex(upper)
  const firstRows = textRows(upper.slice(0, mid))
  const secondRows = textRows(upper.slice(mid))
  const mark = secondRows[0] ? " ".repeat(Math.max(0, Math.floor(secondRows[0].length / 2) - 1) + 1) + "▄" : ""
  return {
    left: ["", firstRows[0] ?? "", firstRows[1] ?? "", firstRows[2] ?? ""],
    right: [mark, secondRows[0] ?? "", secondRows[1] ?? "", secondRows[2] ?? ""],
  }
}

// Single-color wordmark banner (4 rows) for non-TTY CLI output.
export function brandLines(name = Brand.name): string[] {
  const rows = textRows(name.toUpperCase())
  const mark = rows[0] ? " ".repeat(Math.max(0, Math.floor(rows[0].length / 2) - 1) + 1) + "▄" : ""
  return [mark, rows[0] ?? "", rows[1] ?? "", rows[2] ?? ""]
}

// Compact single-letter mark (3 rows) used by the splash banner.
export function brandMark(name = Brand.name): string[] {
  return letter(name.charAt(0)).map((row) => row.trimEnd())
}

export type WordmarkCell = { x: number; y: number; width: number; height: number }

// Block wordmark decomposed into cell rectangles on a unit grid (glyph width
// 5, height 3, one unit gap). Consumers scale by their own cell size to draw
// the wordmark in SVG, free of any font dependency.
export function brandCells(
  name = Brand.name,
): { solid: WordmarkCell[]; top: WordmarkCell[]; bottom: WordmarkCell[] } {
  const solid: WordmarkCell[] = []
  const top: WordmarkCell[] = []
  const bottom: WordmarkCell[] = []
  let x = 0
  for (const char of name) {
    const glyph = letter(char)
    for (let row = 0; row < 3; row++) {
      const line = glyph[row] ?? ""
      for (let col = 0; col < line.length; col++) {
        const cell = line[col]
        if (cell === "█") solid.push({ x: x + col, y: row, width: 1, height: 1 })
        if (cell === "▀") top.push({ x: x + col, y: row, width: 1, height: 0.5 })
        if (cell === "▄") bottom.push({ x: x + col, y: row + 0.5, width: 1, height: 0.5 })
      }
    }
    x += 5 + 1
  }
  return { solid, top, bottom }
}